# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rack-static-if-present}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sam Schenkman-Moore"]
  s.date = %q{2009-12-15}
  s.description = %q{Not much to explain. Not a lot of code, but wanted it packaged up for easy use/deployment.}
  s.email = %q{samsm@samsm.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/rack-static-if-present.rb",
     "test/helper.rb",
     "test/test_rack-static-if-present.rb"
  ]
  s.homepage = %q{http://github.com/samsm/rack-static-if-present}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Like Rack::Static. Except only if there is a static file to serve.}
  s.test_files = [
    "test/helper.rb",
     "test/test_rack-static-if-present.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

